### PR TITLE
Fix getUserFilesDirectory to avoid accessing root privileges in linux

### PR DESCRIPTION
**Pull request by CaulyKan**
Currently, running mcedit2 in linux will attempt to create a folder "MCEdit User Data" under where python executable is, most apparently '/usr/bin/MCEdit User Data'. This will not only force the user to run as root, but also obeys the file system conventions on linux. This fix will try to locate the user data folder at home directory like '/home/xxx/.mcedit'.

Also, I think this statement `if exe.endswith("python") or exe.endswith("python.exe"):` is not proper enough, as it may also cause some strange problems on linux. I'm not sure how should I modify it so I just made a work around of my own.

Thank you!

### CODE REVIEW

**Comment by CaulyKan** [comment]
Also the latter commit provides a workaround for [bug 53](https://github.com/mcedit/mcedit2/issues/53) & [bug 56](https://github.com/mcedit/mcedit2/issues/56) by set the keepExpanded to True for posix systems. 

After the fix the user is able to access the edit UI. However the program crashes when the user tries to manually expand these two nbteditors. I cant figure out why.

**Comment by codewarrior0** [comment]
Thanks for the reminder. I've been meaning to rewrite directories.py at some point to get proper paths on non-Windows systems. Ideally, it should only look at sys.executable when frozen, and then only when set up as a self-contained "portable" installation. The current intent is for source checkouts to keep the user data folder somewhere in the checkout instead of in the same folder used for "regular" non-checkout installations. I'm not sure if that's the best, but I want to keep experimental stuff from contaminating the prefs and such from the release builds. 

Instead of sys.executable, I should use some module's __file__ to find the source checkout folder.

I wouldn't call that a workaround so much as an "experimental result" since you still get a crash when expanding tree nodes. I wrote the NBT editor before I knew very much about Qt's model-view interactions, and I might be doing something wrong with the proxy model, judging by all of the calls to `proxyModel.mapToSource`. If you want to experiment some more, you could try getting rid of the proxy model and see if that changes anything.

I won't merge this as it isn't the right fix, but I'll leave it open for the benefit of other Linux users.

**Comment by CaulyKan** [comment]
Agree. I'll look into the QT's treeview later if I have time(I'm not familiar with QT)

**Comment by codewarrior0** [comment]
As of d1eda07ac17b830940dde5fa5c28df96a109b141, `getUserFilesDirectory` no longer uses `sys.executable` outside of Windows frozen builds. NBT editor's proxy model still needs to be looked at.

**Comment by codewarrior0** [comment]
The problem with the NBT editor is caused by returning the value of a TAG_Long from the model's `data()` function. On Windows, the value is coerced to a string, but on Linux, the value is coerced to a QVariant of type `int` when it should have type `long`. 

This is probably because the QTreeView uses a QSpinBox for the editor widget of a field of integer type, and QSpinBox only accepts `int` and not `long`.

The `TAG_Long` in question is UUIDMost/UUIDLeast.

**Comment by codewarrior0** [comment]
Should be fixed in 73447bee690abee2b00ba691e10f99c769b2abec on the latest master.

**Pull request closed without merging**
